site_name: "RL in Isaac Lab"
repo_url: https://github.com/lajazz23/Unitree-G1-IsaacLab-Locomotion/tree/main
nav:
  - Introduction: index.md
  - Installation: instruction.md
  - Project Structure: about.md
  - Jumpstart: jumpstart.md
  - VR Navigation: vr_nav.md
theme:
  name: material
  custom_dir: overrides
  logo_dark_mode: yellowlogo.png
  logo_light_mode: greenlogo.png
  locale: en
  highlightjs: true
  palette:
    - scheme: default
      primary: light green
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
        
    - scheme: slate
      primary: yellow
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - assets/stylesheets/extra.css