site_name: "Reinforcement Learning in Isaac Lab"
repo_url: https://github.com/lajazz23/Unitree-G1-IsaacLab-Locomotion/tree/main
nav:
  - Introduction: index.md
  - Installation: instruction.md
  - Project Structure: about.md
  - Training: training.md
  - Other: other.md
theme:
  name: dracula
  custom_dir: overrides
  # favicon: assets/favicon.ico
  # logo_dark_mode: assets/yellowlogo.png
  # logo_light_mode: assets/greenlogo.png
  locale: en
  highlightjs: true
  # palette:
  #   - scheme: default
  #     primary: light green
  #     accent: deep orange
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to dark mode
        
  #   - scheme: slate
  #     primary: yellow
  #     accent: pink
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to light mode
  features:
    - content.code.copy
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search